"use strict";

const PROPERTY_LABELS = Object.freeze({
    "actual": "实际参数",
    "additionalModifier": "附加修饰",
    "aggregation": "聚合",
    "arguments": "实参",
    "assignmentTarget": "赋值目标",
    "association": "关联",
    "associationDirection": "关联方向",
    "associationSide": "关联端",
    "author": "作者",
    "body": "主体",
    "calledRef": "调用引用",
    "cancelActivity": "取消活动",
    "cardinality": "基数",
    "checked": "选中",
    "classSide": "类端",
    "classifier": "分类器",
    "company": "公司",
    "completionQuantity": "完成数量",
    "concern": "关注点",
    "concurrency": "并发方式",
    "condition": "条件",
    "connector": "连接器",
    "constrainedElements": "受约束元素",
    "content": "内容",
    "conveyed": "传递项",
    "copyright": "版权",
    "cores": "核心数",
    "covered": "覆盖对象",
    "dashed": "虚线",
    "default": "默认流",
    "defaultDiagram": "默认图",
    "defaultValue": "默认值",
    "definingFeature": "定义特征",
    "description": "描述",
    "direction": "方向",
    "discriminator": "判别器",
    "diskType": "磁盘类型",
    "disks": "磁盘数",
    "documentVersion": "文档版本",
    "end1": "端点 1",
    "end2": "端点 2",
    "entry": "入口点",
    "eventGatewayType": "事件网关类型",
    "exceptionTypes": "异常类型",
    "exit": "出口点",
    "expanded": "展开",
    "expandedInfo": "展开信息",
    "expression": "表达式",
    "extensionLocations": "扩展位置",
    "extensionPoints": "扩展点",
    "featureDirection": "特征方向",
    "fileName": "文件名",
    "foreignKey": "外键",
    "formal": "形式参数",
    "gatewayDirection": "网关方向",
    "guard": "守卫条件",
    "handlerBody": "处理程序主体",
    "height": "高度",
    "hidden": "隐藏",
    "icon": "图标",
    "id": "标识",
    "image": "图像",
    "implementation": "实现",
    "importedElements": "导入元素",
    "inStates": "所在状态",
    "initiatingParticipant": "发起参与者",
    "instantiate": "实例化",
    "interactionOperator": "交互运算符",
    "invariant": "不变式",
    "isAbstract": "抽象",
    "isActive": "主动",
    "isBehavior": "行为端口",
    "isClosed": "封闭",
    "isCollection": "集合",
    "isConcurrentIteration": "并发迭代",
    "isConjugated": "共轭",
    "isControlType": "控制类型",
    "isDerived": "派生",
    "isEncapsulated": "封装",
    "isExecutable": "可执行",
    "isFinalSpecialization": "最终特化",
    "isForCompensation": "用于补偿",
    "isGlobal": "全局",
    "isID": "标识属性",
    "isImmediate": "立即",
    "isIndirectlyInstantiated": "间接实例化",
    "isInterrupting": "中断",
    "isLeaf": "叶节点",
    "isLocallyReentrant": "局部可重入",
    "isLoop": "循环",
    "isMultiInstance": "多实例",
    "isOrdered": "有序",
    "isQuery": "查询",
    "isReadOnly": "只读",
    "isReentrant": "可重入",
    "isSequential": "顺序执行",
    "isService": "服务端口",
    "isSingleExecution": "单次执行",
    "isStatic": "静态",
    "isSynchronous": "同步",
    "isUnique": "唯一",
    "isVertical": "垂直",
    "itemProperty": "项属性",
    "iteration": "迭代",
    "kind": "种类",
    "language": "语言",
    "length": "长度",
    "linkSide": "链接端",
    "location": "位置",
    "loopExpression": "循环表达式",
    "loopType": "循环类型",
    "lowerParticipants": "下方参与者",
    "machineType": "机器类型",
    "mapping": "映射",
    "max": "最大值",
    "maximum": "最大数量",
    "messageRef": "消息引用",
    "messageSort": "消息类型",
    "min": "最小值",
    "minimum": "最小数量",
    "mode": "模式",
    "multiInstance": "多实例",
    "multiInstanceBehavior": "多实例行为",
    "multiplicity": "多重性",
    "mustIsolate": "必须隔离",
    "name": "名称",
    "navigable": "可导航性",
    "nullable": "允许空值",
    "number": "数值",
    "objectSide": "对象端",
    "options": "选项",
    "ordering": "排序方式",
    "orientation": "朝向",
    "ownerAttribute": "所属属性",
    "parallelMultiple": "并行多重",
    "parameter": "参数",
    "parameterType": "参数类型",
    "parameters": "参数",
    "pathType": "路径类型",
    "position": "位置",
    "presentation": "呈现方式",
    "primaryKey": "主键",
    "processType": "流程类型",
    "product": "产品",
    "property": "属性",
    "purpose": "目的",
    "qualifiers": "限定符",
    "quantityKind": "量的种类",
    "raisedExceptions": "引发的异常",
    "ram": "内存",
    "realizingActivityEdges": "实现活动边",
    "realizingConnectors": "实现连接器",
    "realizingMessages": "实现消息",
    "reference": "引用",
    "referenceTo": "引用目标",
    "refersTo": "引用对象",
    "represent": "表示对象",
    "represented": "被表示对象",
    "returnValue": "返回值",
    "returnValueRecipient": "返回值接收方",
    "roleName": "角色名称",
    "rounded": "圆角",
    "script": "脚本",
    "scriptFormat": "脚本格式",
    "selector": "选择器",
    "sequenceNumber": "序列号",
    "sequenceNumbering": "序列编号方式",
    "setting": "设置",
    "showActivation": "显示激活",
    "showName": "显示名称",
    "showSequenceNumber": "显示序列号",
    "showSignature": "显示签名",
    "signal": "信号",
    "signature": "签名",
    "source": "源",
    "specification": "规约",
    "stakeholders": "利益相关者",
    "startQuantity": "开始数量",
    "stereotype": "构造型",
    "subactivity": "子活动",
    "submachine": "子状态机",
    "target": "目标",
    "targetOperation": "目标操作",
    "targetSignal": "目标信号",
    "technology": "技术",
    "testBefore": "先判断条件",
    "text": "文本",
    "triggeredByEvent": "由事件触发",
    "type": "类型",
    "unique": "唯一",
    "unit": "单位",
    "upperParticipants": "上方参与者",
    "url": "链接地址",
    "value": "值",
    "version": "版本",
    "viewpoint": "视点",
    "visibility": "可见性",
    "weight": "权重",
    "width": "宽度",
    "zoneType": "区域类型",
    "identifying": "标识关系"
});

const PROPERTY_OVERRIDES = Object.freeze({
    "Tag": {
        "kind": "标签类型"
    },
    "UMLAction": {
        "kind": "动作类型"
    },
    "UMLPseudostate": {
        "kind": "伪状态类型"
    },
    "UMLTransition": {
        "kind": "迁移类型"
    },
    "UMLEvent": {
        "kind": "事件类型"
    },
    "UMLConnector": {
        "kind": "连接器类型"
    },
    "C4Container": {
        "kind": "容器类型"
    },
    "BPMNExclusiveGateway": {
        "default": "默认序列流"
    },
    "BPMNInclusiveGateway": {
        "default": "默认序列流"
    },
    "BPMNComplexGateway": {
        "default": "默认序列流"
    }
});

const ENUM_LABELS = Object.freeze({
    "TagKind": {
        "string": "字符串",
        "reference": "引用",
        "boolean": "布尔值",
        "number": "数值",
        "enum": "枚举"
    },
    "UMLVisibilityKind": {
        "public": "公有",
        "protected": "受保护",
        "private": "私有",
        "package": "包内"
    },
    "UMLAggregationKind": {
        "none": "无",
        "shared": "共享聚合",
        "composite": "组合"
    },
    "UMLNavigableKind": {
        "unspecified": "未指定",
        "navigable": "可导航",
        "notNavigable": "不可导航"
    },
    "UMLFeatureDirectionKind": {
        "provided": "提供",
        "required": "需要",
        "providedRequired": "提供并需要"
    },
    "UMLDirectionKind": {
        "in": "输入",
        "inout": "输入输出",
        "out": "输出",
        "return": "返回"
    },
    "UMLCallConcurrencyKind": {
        "sequential": "顺序",
        "guarded": "互斥执行",
        "concurrent": "并发"
    },
    "UMLConnectorKind": {
        "assembly": "装配",
        "delegation": "委派"
    },
    "UMLMessageSort": {
        "synchCall": "同步调用",
        "asynchCall": "异步调用",
        "asynchSignal": "异步信号",
        "createMessage": "创建消息",
        "deleteMessage": "删除消息",
        "reply": "应答"
    },
    "UMLPseudostateKind": {
        "initial": "初始",
        "deepHistory": "深历史",
        "shallowHistory": "浅历史",
        "join": "汇合",
        "fork": "分叉",
        "junction": "连接点",
        "choice": "选择",
        "entryPoint": "入口点",
        "exitPoint": "出口点",
        "terminate": "终止"
    },
    "UMLTransitionKind": {
        "external": "外部",
        "internal": "内部",
        "local": "局部"
    },
    "UMLEventKind": {
        "signal": "信号",
        "call": "调用",
        "change": "变更",
        "time": "时间",
        "anyReceive": "任意接收"
    },
    "UMLInteractionOperatorKind": {
        "alt": "择一",
        "opt": "可选",
        "par": "并行",
        "loop": "循环",
        "critical": "临界",
        "neg": "否定",
        "assert": "断言",
        "strict": "严格顺序",
        "seq": "弱顺序",
        "ignore": "忽略",
        "consider": "考虑",
        "break": "中断"
    },
    "UMLActionKind": {
        "opaque": "不透明",
        "create": "创建",
        "destroy": "销毁",
        "read": "读取",
        "write": "写入",
        "insert": "插入",
        "delete": "删除",
        "sendSignal": "发送信号",
        "acceptSignal": "接收信号",
        "triggerEvent": "触发事件",
        "acceptEvent": "接收事件",
        "structured": "结构化",
        "timeEvent": "时间事件",
        "callBehavior": "调用行为",
        "callOperation": "调用操作"
    },
    "UMLObjectNodeOrderingKind": {
        "unordered": "无序",
        "ordered": "有序",
        "LIFO": "后进先出",
        "FIFO": "先进先出"
    },
    "UMLExpansionKind": {
        "parallel": "并行",
        "iterative": "迭代",
        "stream": "流式"
    },
    "UMLStereotypeDisplayKind": {
        "none": "无",
        "label": "标签",
        "decoration": "装饰",
        "decoration-label": "装饰与标签",
        "icon": "图标",
        "icon-label": "图标与标签"
    },
    "UMLSequenceNumberingKind": {
        "auto": "自动",
        "custom": "自定义"
    },
    "BPMNProcessType": {
        "none": "无",
        "public": "公共",
        "private": "私有"
    },
    "BPMNGatewayDirection": {
        "unspecified": "未指定",
        "converging": "汇聚",
        "diverging": "分流",
        "mixed": "混合"
    },
    "BPMNEventBasedGatewayType": {
        "parallel": "并行",
        "exclusive": "排他"
    },
    "BPMNAssociationDirection": {
        "none": "无",
        "one": "单向",
        "both": "双向"
    },
    "BPMNMultiInstanceBehavior": {
        "none": "无",
        "one": "一个",
        "all": "全部",
        "complex": "复杂"
    },
    "BPMNChoreographyLoopType": {
        "none": "无",
        "standard": "标准",
        "multiInstanceSequential": "顺序多实例",
        "multiInstanceParallel": "并行多实例"
    },
    "C4ContainerKind": {
        "server-webapp": "服务端 Web 应用",
        "client-webapp": "客户端 Web 应用",
        "desktop-app": "桌面应用",
        "mobile-app": "移动应用",
        "console-app": "控制台应用",
        "serverless-function": "无服务器函数",
        "database": "数据库",
        "blob-store": "对象存储",
        "filesystem": "文件系统",
        "shell-script": "Shell 脚本",
        "etc": "其他"
    },
    "GCPPathKind": {
        "primary": "主要",
        "optional-primary": "可选主要",
        "secondary": "次要",
        "optional-secondary": "可选次要",
        "success": "成功",
        "failure": "失败"
    },
    "GCPZoneKind": {
        "project": "项目",
        "logical-group": "逻辑分组",
        "region": "区域",
        "zone": "可用区",
        "sub-network": "子网",
        "firewall": "防火墙",
        "instance-group": "实例组",
        "replica-pool": "副本池",
        "kubernetes-cluster": "Kubernetes 集群",
        "pod": "Pod",
        "account": "账号",
        "optional": "可选",
        "system": "系统",
        "infrastructure-system": "基础设施系统",
        "on-premises": "本地部署",
        "external-saas-providers": "外部 SaaS 提供商",
        "external-data-sources": "外部数据源",
        "external-thirdparty-infrastructure": "外部第三方基础设施",
        "external-firstparty-infrastructure": "外部自有基础设施",
        "user": "用户"
    },
    "GCPMachineType": {
        "none": "无",
        "standard": "标准",
        "shared-core-f1": "共享核心（f1）",
        "shared-core-g1": "共享核心（g1）",
        "high-cpu": "高 CPU",
        "high-memory": "高内存",
        "custom-virtual": "自定义虚拟机"
    },
    "GCPDiskType": {
        "none": "无",
        "pd": "标准永久磁盘",
        "pd-ssd": "SSD 永久磁盘",
        "local-ssd": "本地 SSD"
    },
    "GCPAdditionalModifierType": {
        "none": "无",
        "autoscaling": "自动扩缩容",
        "preemptable": "可抢占"
    },
    "SysMLFlowDirectionKind": {
        "in": "输入",
        "out": "输出",
        "inout": "输入输出"
    },
    "SysMLFeatureDirectionKind": {
        "provided": "提供",
        "required": "需要",
        "providedRequired": "提供并需要"
    },
    "WFOrientationKind": {
        "portrait": "纵向",
        "landscape": "横向"
    },
    "WFPositionKind": {
        "top": "顶部",
        "bottom": "底部",
        "left": "左侧",
        "right": "右侧"
    }
});

const TYPE_LABELS = Object.freeze({
    "Element": "元素",
    "Model": "模型",
    "Tag": "标签",
    "Hyperlink": "超链接",
    "ExtensibleModel": "可扩展模型",
    "Relationship": "关系",
    "DirectedRelationship": "有向关系",
    "RelationshipEnd": "关系端",
    "UndirectedRelationship": "无向关系",
    "Diagram": "图",
    "Project": "项目",
    "AWSElement": "AWS 元素",
    "AWSModel": "AWS 模型",
    "AWSDiagram": "AWS 架构图",
    "AWSGroup": "AWS 分组",
    "AWSGenericGroup": "AWS 通用分组",
    "AWSAvailabilityZone": "AWS 可用区",
    "AWSSecurityGroup": "AWS 安全组",
    "AWSService": "AWS 服务",
    "AWSResource": "AWS 资源",
    "AWSGeneralResource": "AWS 通用资源",
    "AWSCallout": "AWS 标注",
    "AWSArrow": "AWS 箭头",
    "AzureElement": "Azure 元素",
    "AzureModel": "Azure 模型",
    "AzureDiagram": "Azure 架构图",
    "AzureGroup": "Azure 分组",
    "AzureService": "Azure 服务",
    "AzureCallout": "Azure 标注",
    "AzureConnector": "Azure 连接线",
    "BPMNDiagram": "BPMN 图",
    "BPMNBaseElement": "BPMN 基础元素",
    "BPMNRootElement": "BPMN 根元素",
    "BPMNCollaboration": "协作",
    "BPMNChoreography": "协同编排",
    "BPMNGlobalConversation": "全局会话",
    "BPMNParticipant": "参与者",
    "BPMNLane": "泳道",
    "BPMNProcess": "流程",
    "BPMNFlowElement": "流程元素",
    "BPMNActivity": "活动",
    "BPMNCallActivity": "调用活动",
    "BPMNTask": "任务",
    "BPMNSendTask": "发送任务",
    "BPMNReceiveTask": "接收任务",
    "BPMNServiceTask": "服务任务",
    "BPMNUserTask": "用户任务",
    "BPMNManualTask": "手工任务",
    "BPMNBusinessRuleTask": "业务规则任务",
    "BPMNScriptTask": "脚本任务",
    "BPMNSubProcess": "子流程",
    "BPMNAdHocSubProcess": "即席子流程",
    "BPMNTransaction": "事务",
    "BPMNChoreographyActivity": "协同编排活动",
    "BPMNChoreographyTask": "协同编排任务",
    "BPMNSubChoreography": "子协同编排",
    "BPMNCallChoreography": "调用协同编排",
    "BPMNEventDefinition": "事件定义",
    "BPMNCompensateEventDefinition": "补偿事件定义",
    "BPMNCancelEventDefinition": "取消事件定义",
    "BPMNErrorEventDefinition": "错误事件定义",
    "BPMNLinkEventDefinition": "链接事件定义",
    "BPMNSignalEventDefinition": "信号事件定义",
    "BPMNTimerEventDefinition": "定时器事件定义",
    "BPMNEscalationEventDefinition": "升级事件定义",
    "BPMNMessageEventDefinition": "消息事件定义",
    "BPMNTerminateEventDefinition": "终止事件定义",
    "BPMNConditionalEventDefinition": "条件事件定义",
    "BPMNEvent": "事件",
    "BPMNThrowEvent": "抛出事件",
    "BPMNCatchEvent": "捕获事件",
    "BPMNImplicitThrowEvent": "隐式抛出事件",
    "BPMNIntermediateThrowEvent": "中间抛出事件",
    "BPMNEndEvent": "结束事件",
    "BPMNStartEvent": "开始事件",
    "BPMNIntermediateCatchEvent": "中间捕获事件",
    "BPMNBoundaryEvent": "边界事件",
    "BPMNGateway": "网关",
    "BPMNExclusiveGateway": "排他网关",
    "BPMNInclusiveGateway": "包容网关",
    "BPMNParallelGateway": "并行网关",
    "BPMNComplexGateway": "复杂网关",
    "BPMNEventBasedGateway": "事件网关",
    "BPMNItemAwareElement": "数据感知元素",
    "BPMNDataObject": "数据对象",
    "BPMNDataStore": "数据存储",
    "BPMNDataInput": "数据输入",
    "BPMNDataOutput": "数据输出",
    "BPMNMessage": "消息",
    "BPMNConversationNode": "会话节点",
    "BPMNConversation": "会话",
    "BPMNSubConversation": "子会话",
    "BPMNCallConversation": "调用会话",
    "BPMNConversationLink": "会话连接",
    "BPMNArtifact": "制品",
    "BPMNTextAnnotation": "文本注释",
    "BPMNGroup": "分组",
    "BPMNAssociation": "关联",
    "BPMNDataAssociation": "数据关联",
    "BPMNSequenceFlow": "顺序流",
    "BPMNMessageFlow": "消息流",
    "BPMNMessageLink": "消息连接",
    "C4Element": "C4 元素",
    "C4Model": "C4 模型",
    "C4Diagram": "C4 图",
    "C4Person": "人员",
    "C4SoftwareSystem": "软件系统",
    "C4Container": "容器",
    "C4Component": "组件",
    "C4Relationship": "C4 关系",
    "DFDElement": "数据流元素",
    "DFDDataFlowModel": "数据流模型",
    "DFDExternalEntity": "外部实体",
    "DFDProcess": "处理过程",
    "DFDDataStore": "数据存储",
    "DFDDataFlow": "数据流",
    "DFDDiagram": "数据流图",
    "ERDElement": "实体关系元素",
    "ERDDataModel": "数据模型",
    "ERDDiagram": "实体关系图",
    "ERDColumn": "列",
    "ERDEntity": "实体",
    "ERDRelationshipEnd": "实体关系端",
    "ERDRelationship": "实体关系",
    "FCModelElement": "流程图元素",
    "FCFlowchart": "流程模型",
    "FCFlowchartDiagram": "流程图",
    "FCProcess": "处理",
    "FCTerminator": "起止符",
    "FCDecision": "判断",
    "FCDelay": "延迟",
    "FCPredefinedProcess": "预定义处理",
    "FCAlternateProcess": "替代处理",
    "FCData": "数据",
    "FCDocument": "文档",
    "FCMultiDocument": "多文档",
    "FCPreparation": "准备",
    "FCDisplay": "显示",
    "FCManualInput": "手动输入",
    "FCManualOperation": "手动操作",
    "FCCard": "卡片",
    "FCPunchedTape": "穿孔纸带",
    "FCConnector": "连接点",
    "FCOffPageConnector": "跨页连接点",
    "FCOr": "或",
    "FCSummingJunction": "汇总连接点",
    "FCCollate": "整理",
    "FCSort": "排序",
    "FCMerge": "合并",
    "FCExtract": "提取",
    "FCStoredData": "存储数据",
    "FCDatabase": "数据库",
    "FCDirectAccessStorage": "直接访问存储",
    "FCInternalStorage": "内部存储",
    "FCFlow": "流程线",
    "GCPElement": "GCP 元素",
    "GCPModel": "GCP 模型",
    "GCPDiagram": "GCP 架构图",
    "GCPUser": "GCP 用户",
    "GCPZone": "GCP 区域",
    "GCPProduct": "GCP 产品",
    "GCPService": "GCP 服务",
    "GCPPath": "GCP 路径",
    "MMElement": "思维导图元素",
    "MMMindmap": "思维导图模型",
    "MMMindmapDiagram": "思维导图",
    "MMNode": "主题节点",
    "MMEdge": "主题连接线",
    "SysMLDiagram": "SysML 图",
    "SysMLRequirementDiagram": "需求图",
    "SysMLBlockDefinitionDiagram": "块定义图",
    "SysMLInternalBlockDiagram": "内部块图",
    "SysMLParametricDiagram": "参数图",
    "SysMLStakeholder": "利益相关者",
    "SysMLView": "视图",
    "SysMLViewpoint": "视点",
    "SysMLConform": "符合",
    "SysMLExpose": "暴露",
    "SysMLAbstractRequirement": "抽象需求",
    "SysMLRequirement": "需求",
    "SysMLTrace": "追踪",
    "SysMLCopy": "复制",
    "SysMLDeriveReqt": "派生需求",
    "SysMLVerify": "验证",
    "SysMLSatisfy": "满足",
    "SysMLRefine": "精化",
    "SysMLProperty": "属性",
    "SysMLFlowProperty": "流属性",
    "SysMLBlock": "块",
    "SysMLValueType": "值类型",
    "SysMLInterfaceBlock": "接口块",
    "SysMLPort": "端口",
    "SysMLConnector": "连接器",
    "SysMLItemFlow": "项流",
    "SysMLConstraintBlock": "约束块",
    "SysMLPropertyValueCompartmentItemView": "属性值条目视图",
    "UMLModelElement": "UML 模型元素",
    "UMLTemplateParameter": "模板参数",
    "UMLTemplateParameterSubstitution": "模板参数替换",
    "UMLFeature": "特征",
    "UMLStructuralFeature": "结构特征",
    "UMLParameter": "参数",
    "UMLBehavioralFeature": "行为特征",
    "UMLAttribute": "属性",
    "UMLOperation": "操作",
    "UMLReception": "接收",
    "UMLClassifier": "分类器",
    "UMLDirectedRelationship": "有向关系",
    "UMLRelationshipEnd": "关系端",
    "UMLUndirectedRelationship": "无向关系",
    "UMLConstraint": "约束",
    "UMLIntervalConstraint": "区间约束",
    "UMLTimeConstraint": "时间约束",
    "UMLDurationConstraint": "持续时间约束",
    "UMLBehavior": "行为",
    "UMLOpaqueBehavior": "不透明行为",
    "UMLEvent": "事件",
    "UMLPackage": "包",
    "UMLModel": "UML 模型",
    "UMLClass": "类",
    "UMLInterface": "接口",
    "UMLSignal": "信号",
    "UMLDataType": "数据类型",
    "UMLPrimitiveType": "基本类型",
    "UMLEnumerationLiteral": "枚举字面量",
    "UMLEnumeration": "枚举",
    "UMLDependency": "依赖",
    "UMLAbstraction": "抽象",
    "UMLRealization": "实现",
    "UMLGeneralization": "泛化",
    "UMLInterfaceRealization": "接口实现",
    "UMLComponentRealization": "组件实现",
    "UMLAssociationEnd": "关联端",
    "UMLAssociation": "关联",
    "UMLAssociationClassLink": "关联类连接",
    "UMLNaryAssociationNode": "多元关联节点",
    "UMLTemplateBinding": "模板绑定",
    "UMLSlot": "槽",
    "UMLInstance": "实例",
    "UMLObject": "对象",
    "UMLArtifactInstance": "制品实例",
    "UMLComponentInstance": "组件实例",
    "UMLNodeInstance": "节点实例",
    "UMLLinkEnd": "链接端",
    "UMLLink": "链接",
    "UMLLinkObjectLink": "链接对象连接",
    "UMLPort": "端口",
    "UMLConnectorEnd": "连接器端",
    "UMLConnector": "连接器",
    "UMLCollaboration": "协作",
    "UMLCollaborationUse": "协作使用",
    "UMLRoleBinding": "角色绑定",
    "UMLArtifact": "制品",
    "UMLComponent": "组件",
    "UMLSubsystem": "子系统",
    "UMLNode": "节点",
    "UMLDeployment": "部署",
    "UMLCommunicationPath": "通信路径",
    "UMLExtensionPoint": "扩展点",
    "UMLUseCase": "用例",
    "UMLActor": "参与者",
    "UMLInclude": "包含",
    "UMLExtend": "扩展",
    "UMLUseCaseSubject": "用例主体",
    "UMLStateMachine": "状态机",
    "UMLRegion": "区域",
    "UMLVertex": "顶点",
    "UMLPseudostate": "伪状态",
    "UMLConnectionPointReference": "连接点引用",
    "UMLState": "状态",
    "UMLFinalState": "终止状态",
    "UMLTransition": "迁移",
    "UMLActivity": "活动",
    "UMLPin": "引脚",
    "UMLInputPin": "输入引脚",
    "UMLOutputPin": "输出引脚",
    "UMLExpansionNode": "扩展节点",
    "UMLActivityNode": "活动节点",
    "UMLAction": "动作",
    "UMLStructuredActivityNode": "结构化活动节点",
    "UMLExpansionRegion": "扩展区域",
    "UMLObjectNode": "对象节点",
    "UMLCentralBufferNode": "中央缓冲节点",
    "UMLDataStoreNode": "数据存储节点",
    "UMLActivityParameterNode": "活动参数节点",
    "UMLControlNode": "控制节点",
    "UMLInitialNode": "初始节点",
    "UMLFinalNode": "终止节点",
    "UMLActivityFinalNode": "活动终止节点",
    "UMLFlowFinalNode": "流终止节点",
    "UMLForkNode": "分叉节点",
    "UMLJoinNode": "汇合节点",
    "UMLMergeNode": "合并节点",
    "UMLDecisionNode": "判定节点",
    "UMLActivityGroup": "活动组",
    "UMLActivityPartition": "活动分区",
    "UMLInterruptibleActivityRegion": "可中断活动区域",
    "UMLActivityEdgeConnector": "活动边连接器",
    "UMLExceptionHandler": "异常处理程序",
    "UMLActivityEdge": "活动边",
    "UMLControlFlow": "控制流",
    "UMLObjectFlow": "对象流",
    "UMLActivityInterrupt": "活动中断",
    "UMLInteractionFragment": "交互片段",
    "UMLInteraction": "交互",
    "UMLStateInvariant": "状态不变式",
    "UMLContinuation": "延续",
    "UMLInteractionOperand": "交互操作数",
    "UMLCombinedFragment": "组合片段",
    "UMLInteractionUse": "交互使用",
    "UMLMessageEndpoint": "消息端点",
    "UMLLifeline": "生命线",
    "UMLGate": "门",
    "UMLEndpoint": "端点",
    "UMLMessage": "消息",
    "UMLInformationItem": "信息项",
    "UMLInformationFlow": "信息流",
    "UMLProfile": "UML 剖面",
    "UMLImage": "图像",
    "UMLStereotype": "构造型",
    "UMLMetaClass": "元类",
    "UMLExtension": "扩展",
    "UMLDiagram": "UML 图",
    "UMLClassDiagram": "类图",
    "UMLPackageDiagram": "包图",
    "UMLCompositeStructureDiagram": "组合结构图",
    "UMLObjectDiagram": "对象图",
    "UMLComponentDiagram": "组件图",
    "UMLDeploymentDiagram": "部署图",
    "UMLUseCaseDiagram": "用例图",
    "UMLStatechartDiagram": "状态图",
    "UMLActivityDiagram": "活动图",
    "UMLSequenceDiagram": "时序图",
    "UMLCommunicationDiagram": "通信图",
    "UMLTimingDiagram": "定时图",
    "UMLInteractionOverviewDiagram": "交互概览图",
    "UMLInformationFlowDiagram": "信息流图",
    "UMLProfileDiagram": "UML 剖面图",
    "WFElement": "线框图元素",
    "WFWireframe": "线框模型",
    "WFWireframeDiagram": "线框图",
    "WFFrame": "框架",
    "WFMobileFrame": "移动端框架",
    "WFWebFrame": "网页框架",
    "WFDesktopFrame": "桌面框架",
    "WFButton": "按钮",
    "WFText": "文本",
    "WFRadio": "单选按钮",
    "WFCheckbox": "复选框",
    "WFSwitch": "开关",
    "WFLink": "链接",
    "WFTab": "选项卡",
    "WFTabList": "选项卡列表",
    "WFInput": "输入框",
    "WFDropdown": "下拉框",
    "WFPanel": "面板",
    "WFImage": "图像",
    "WFSeparator": "分隔线",
    "WFAvatar": "头像",
    "WFSlider": "滑块"
});

function hasOwn(table, key) {
    return Object.prototype.hasOwnProperty.call(table, key);
}

function labelFrom(table, key) {
    return table && hasOwn(table, key) ? table[key] : key;
}

/** 返回属性展示名，未知字段保留原标识。 */
function propertyLabel(typeName, field) {
    const overrides = hasOwn(PROPERTY_OVERRIDES, typeName)
        ? PROPERTY_OVERRIDES[typeName]
        : null;
    return overrides && hasOwn(overrides, field)
        ? overrides[field]
        : labelFrom(PROPERTY_LABELS, field);
}

/** enumType 为元模型枚举类型名；返回文本不得作为模型的保存值。 */
function enumLabel(enumType, value) {
    const labels = hasOwn(ENUM_LABELS, enumType) ? ENUM_LABELS[enumType] : null;
    return labelFrom(labels, value);
}

/** 返回类型展示名，不影响默认名称生成或类型识别。 */
function typeLabel(typeName) {
    return labelFrom(TYPE_LABELS, typeName);
}

module.exports = { propertyLabel, enumLabel, typeLabel };
